AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-customer-app-nonproxy

  Sample SAM Template for sam-customer-app-nonproxy

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

Resources:
  CustomerHandlerNPFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: CustomerHandlerNPFunction
      Handler: com.amazonaws.poc.CustomerHandlerNP::handleRequest
      Runtime: java8
      MemorySize: 512
      Events:
        CustomerHandlerNP:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /customer
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  CustomerHandlerNPApi:
    Description: "API Gateway endpoint URL for Prod stage for Customer Handler NP function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/customer"
  CustomerHandlerNPFunction:
    Description: "Customer Handler NP Lambda Function ARN"
    Value: !GetAtt CustomerHandlerNPFunction.Arn
  CustomerHandlerNPFunctionIamRole:
    Description: "Implicit IAM Role created for Customer Handler NP function"
    Value: !GetAtt CustomerHandlerNPFunctionRole.Arn
