version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-customer-app-cfs"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-mkqumqt1ro7i"
s3_prefix = "sam-customer-app-cfs"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
